### ISSUE TITLE
project died?

### ISSUE THREAD

**Issue by jekeam** [positiveway/SureFinder#127]
Good afternoon, curious, why abandoned the project?

**Comment by hezarjaribi** [comment]
> Good afternoon, curious, why abandoned the project?

i think :) but This is not Good , do you agree?

**Comment by jekeam** [comment]
i dont no

**Comment by ghost** [comment]
We moved on to other scraping projects, this project requires a lot of maintenance because sites deploy countermeasures. This project was published for reference purposes. API keys were deleted as well as other private details so you can't launch it right away
